### ISSUE TITLE
Failing POST on /v1/petitions/PETITIONS_ID/signatures

### ISSUE THREAD

**Issue by foxbunny** [change/api_docs#16]
The POST params are as follows:

```
{
'city': 'SNIPPED', 
'first_name': 'SNIPPED', 
'endpoint': '/v1/petitions/PETITIONS_ID/signatures', 
'timestamp': '2014-08-12T18:47:48Z', 
'rsig': '5a67d247b1b67a9d4cc226ea63af1903242a5c1c03ba37eea0ff2667746022d3', 
'last_name': 'SNIPPED', 
'postal_code': 'SNIPPED', 
'country_code': 'SNIPPED', 
'api_key': 'SNIPPED', 
'email': 'SNIPPED'
}
```

I'm getting a HTTP 500. Any idea what I am doing wrong?

**Comment by quaelin** [comment]
This went a long time without getting an answer, sorry about that!

Given that this issue is many months old, I'm going to close it and assume that it's probably no longer relevant.  But please let us know if you have any further issues and we'll endeavor to not let them go unaddressed.
