### ISSUE TITLE
A way to get the number of signed petitions

### ISSUE THREAD

**Issue by hasit** [change/api_docs#18]
Hello.

Is there a way to get the number of signed petitions? I would like to show the number on a website. I was wondering is there a way to do that using this API. Help would be greatly appreciated.

Thank you.

**Comment by quaelin** [comment]
Are you looking for the number of signatures on a given petition, or the number of petitions signed by a given user?

**Comment by hasit** [comment]
Yes. I am looking for the number of signatures on a given petition.

**Comment by quaelin** [comment]
You can just use this endpoint, then:
https://github.com/change/api_docs/blob/master/v1/documentation/resources/petitions/signatures.md#get-petitionspetition_idsignatures

It allows you to page through all the signature data, but you don't have to do that.  Instead, just look for the `signature_count` in the initial response.

**Comment by quaelin** [comment]
Closing this issue, but please re-open if that's not working for you.  :)

**Comment by planethax** [comment]
This is what I found worked,
You will need to put your apI key in and your URL of petition in the function at end

<?php
// get signatures for a Change.org petition
function getChangePetitionSignatureCount($url){
$CHANGE_API_KEY = 'PUTYOUR-API-KEY-HERE';
 $CHANGE_REQUEST_URL = 'https://api.change.org/v1/petitions/get_id';
 $parameters = array(
 'api_key' => $CHANGE_API_KEY,
 'petition_url' => $url
 );
 $query_string = http_build_query($parameters);
 $final_request_url = "$CHANGE_REQUEST_URL?$query_string";
 $response = file_get_contents($final_request_url);
 $json_response = json_decode($response, true);
 $petition_id = $json_response['petition_id'];
 //now get the petition details for signature count
 $CHANGE_REQUEST_URL = 'https://api.change.org/v1/petitions';
 $parameters = array(
 'api_key' => $CHANGE_API_KEY,
 'petition_ids' => $petition_id
 );
 $query_string = http_build_query($parameters);
 $final_request_url = "$CHANGE_REQUEST_URL?$query_string";
 $response = file_get_contents($final_request_url);
 $json_response = json_decode($response, true);
 $petition = $json_response['petitions'][0];
 $sig_count = $petition['signature_count'];
 //var_dump($json_response);
 return $sig_count;
}
echo getChangePetitionSignatureCount("https://www.change.org/PUT-URL-2-UR-PETITION-HERE");
?>

**Comment by doncadavona** [comment]
This has to be **re-opened** due to the **deprecation** of

`GET petitions/:petition_id/signatures`

Without this endpoint, we get the number of signatures on a petition.

Or do they have an alternative endpoint?
