### ISSUE TITLE
"Request API access" link for petition

### ISSUE THREAD

**Issue by sephii** [change/api_docs#24]
https://github.com/change/api_docs/blob/master/v1/tutorials/add-signatures-to-a-petition.md mentions `you can request an authorization key directly on a petition's page on Change.org by clicking on the "Request API access" link at the bottom, right above the footer` but there is no such link.

**Comment by planethax** [comment]
No link there you are right.
From my experience, the first time you use api to try and update signatures, it sends an email to the petition owner telling them someone wants access.
Then you are granted access unless they deny it.
If they do nothing you have access.

**Comment by sephii** [comment]
Yes that's right. The docs should be updated to mention this behavior.

**Comment by planethax** [comment]
the api just went from beta to retired, they won't be updating or repairing.

**Comment by sephii** [comment]
Damn, they could have at least updated their developer docs page. Thanks for the info!
